// // Print Area of a Rectangle:
//  Task: Create a flowchart to calculate and print the area of a rectangle.
//  Next Step: Write a Java program that calculates the area of a rectangle using the formula
// area = length * width. Use predefined values for length and width

public class Q6 {
    public static void main(String[] args) {
    int l=5,b=6;
    int aor=l*b;
    System.out.println("Area of a Rectangle:-"+aor);    
    }
}
